### ISSUE TITLE
Support comments in bitquery

### ISSUE THREAD

**Issue by Ljzn** [interplanaria/planaria#14]
example: 
```js
// A query lists all twetch
// author: _unwriter
{
  "v": 3,
  ...
```

help people to share and reuse their bitquery.

**Comment by breavyn** [comment]
bitquery queries are JSON objects. JSON doesn't have provision for comments. Refer to [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
